<?php
$z[0]=Array("field","",274,293);
$z[0][4]['name']="title";
$z[1]=Array("global","",294,320);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",361,383);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",423,474);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",564,589);
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("include","",1041,1076);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",1222,1280);
$z[6][4]['name']="typeid";
$z[6][4]['function']="GetTopTypename(@me)";
$z[7]=Array("channel","\r\n      <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n      ",1392,1597);
$z[7][4]['type']="son";
$z[7][4]['currentstyle']="<li class='current'><a href='~typelink~'>~typename~</a></li>";
$z[8]=Array("type"," <a class=\"fr\" href=\"[field:typelink/]\">返回目录</a>",1713,1792);
$z[9]=Array("field","",1873,1892);
$z[9][4]['name']="title";
$z[10]=Array("field","",1927,1983);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[11]=Array("field","",2001,2019);
$z[11][4]['name']="body";
$z[12]=Array("include","",2068,2105);
$z[12][4]['filename']="footer.htm";

?>