<?php
$z[0]=Array("global","",313,334);
$z[0][4]['name']="cfg_qq";
$z[1]=Array("global","",557,578);
$z[1][4]['name']="cfg_qq";
$z[2]=Array("sql"," \r\n        [field:content  function='cn_substr(html2text(@me),300)'/]...\r\n        ",906,1059);
$z[2][4]['sql']="Select content from dede_arctype where id=1";
$z[3]=Array("type"," <a href=\"[field:typelink/]\">Learn More</a>",1073,1150);
$z[3][4]['typeid']="1";
$z[4]=Array("global","",1255,1276);
$z[4][4]['name']="cfg_rx";
$z[5]=Array("global","",1309,1331);
$z[5][4]['name']="cfg_tel";
$z[6]=Array("global","",1366,1387);
$z[6][4]['name']="cfg_yx";
$z[7]=Array("global","",1429,1451);
$z[7][4]['name']="cfg_add";
$z[8]=Array("global","",1571,1592);
$z[8][4]['name']="cfg_qq";
$z[9]=Array("global","",1656,1677);
$z[9][4]['name']="cfg_qq";
$z[10]=Array("global","",2061,2087);
$z[10][4]['name']="cfg_powerby";

?>