<?php
$z[0]=Array("global","",114,140);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("channel","\r\n        <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n        ",239,480);
$z[1][4]['type']="top";
$z[1][4]['row']="10";
$z[1][4]['currentstyle']="<li class='current'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[2]=Array("global","",638,659);
$z[2][4]['name']="cfg_rx";

?>